# Generated by Django 5.1.15 on 2026-03-30 06:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique programmatic identifier (e.g. 'first_win').",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.TextField(
                        help_text="Player-facing description of how to unlock."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wins", "Wins"),
                            ("games", "Games Played"),
                            ("streaks", "Streaks"),
                            ("skill", "Skill"),
                            ("social", "Social"),
                            ("milestone", "Milestone"),
                        ],
                        db_index=True,
                        default="milestone",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=12,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="trophy",
                        help_text="Icon identifier used by the frontend.",
                        max_length=60,
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="XP granted when the achievement is unlocked.",
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Target value for progress-based achievements.",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden achievements are not shown until unlocked.",
                    ),
                ),
                (
                    "ordering_priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower = displayed first within a category.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "db_table": "achievements",
                "ordering": ["category", "ordering_priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="AchievementProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="analytics.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement Progress",
                "verbose_name_plural": "Achievement Progress",
                "db_table": "achievement_progress",
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="AchievementUnlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "game_session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The game session that triggered this unlock (if any).",
                        max_length=100,
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="analytics.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_unlocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement Unlock",
                "verbose_name_plural": "Achievement Unlocks",
                "db_table": "achievement_unlocks",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("game", "Game"),
                            ("achievement", "Achievement"),
                            ("social", "Social"),
                            ("profile", "Profile"),
                            ("navigation", "Navigation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Fine-grained event name within its category, e.g. 'login', 'match_completed', 'achievement_unlocked'.",
                        max_length=60,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary event-specific payload (scores, IPs, etc.).",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP at the time of the event.",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Browser / client user-agent string.",
                        max_length=512,
                    ),
                ),
                (
                    "is_anonymised",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="If True, metadata has been scrubbed for privacy.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Event",
                "verbose_name_plural": "Activity Events",
                "db_table": "activity_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_activity_user_created"
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="idx_activity_cat_created",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="idx_activity_type_created",
                    ),
                    models.Index(
                        fields=["user", "category", "-created_at"],
                        name="idx_activity_user_cat",
                    ),
                ],
            },
        ),
    ]
