# Generated by Django 5.1.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="category",
            field=models.CharField(
                choices=[
                    ("pong", "Pong"),
                    ("tictactoe", "Tic-Tac-Toe"),
                    ("level", "Player Level"),
                ],
                db_index=True,
                default="pong",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="tier",
            field=models.CharField(
                choices=[
                    ("common", "Common"),
                    ("rare", "Rare"),
                    ("epic", "Epic"),
                    ("legendary", "Legendary"),
                ],
                default="common",
                max_length=12,
            ),
        ),
    ]
