from django.urls import path
from .views import (
    # Achievement endpoints
    AchievementDetailView,
    AchievementListView,
    AchievementProgressListView,
    AchievementStatsView,
    AchievementUnlockedListView,
    LeaderboardView,
    LevelTableView,
    UserXPDetailView,
    ActivityHeatmapView,
    ActivitySummaryView,
    ActivityTimelineView,
    AnonymiseActivityView,
    ExportActivityView,
    GlobalActivitySummaryView,
    RecentActivityView,
    TrackEventView,
)

urlpatterns = [
    path(
        "achievements/",
        AchievementListView.as_view(),
        name="achievement-list",
    ),
    path(
        "achievements/unlocked/",
        AchievementUnlockedListView.as_view(),
        name="achievement-unlocked-list",
    ),
    path(
        "achievements/progress/",
        AchievementProgressListView.as_view(),
        name="achievement-progress-list",
    ),
    path(
        "achievements/stats/",
        AchievementStatsView.as_view(),
        name="achievement-stats",
    ),
    path(
        "achievements/<uuid:pk>/",
        AchievementDetailView.as_view(),
        name="achievement-detail",
    ),

    path(
        "leaderboard/",
        LeaderboardView.as_view(),
        name="leaderboard",
    ),
    path(
        "xp/me/",
        UserXPDetailView.as_view(),
        name="user-xp-detail",
    ),
    path(
        "xp/levels/",
        LevelTableView.as_view(),
        name="level-table",
    ),
    path(
        "activity/summary/",
        ActivitySummaryView.as_view(),
        name="activity-summary",
    ),
    path(
        "activity/timeline/",
        ActivityTimelineView.as_view(),
        name="activity-timeline",
    ),
    path(
        "activity/heatmap/",
        ActivityHeatmapView.as_view(),
        name="activity-heatmap",
    ),
    path(
        "activity/recent/",
        RecentActivityView.as_view(),
        name="activity-recent",
    ),
    path(
        "activity/track/",
        TrackEventView.as_view(),
        name="activity-track",
    ),
    path(
        "activity/export/",
        ExportActivityView.as_view(),
        name="activity-export",
    ),
    path(
        "activity/anonymise/",
        AnonymiseActivityView.as_view(),
        name="activity-anonymise",
    ),
    path(
        "activity/global/",
        GlobalActivitySummaryView.as_view(),
        name="activity-global",
    ),
]
