# Generated by Django 5.1.15 on 2026-03-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverificationtoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailverificationtoken",
            new_name="email_verif_user_id_3f815d_idx",
            old_name="email_verif_user_id_token_type_used_idx",
        ),
    ]
