# Generated by Django 5.1.15 on 2026-03-30 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "game_session_id",
                    models.CharField(
                        db_index=True,
                        help_text="In-memory session ID from GameSession.game_id.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[("pong", "Pong"), ("tictactoe", "Tic-Tac-Toe")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "game_mode",
                    models.CharField(
                        choices=[("pvp", "Player vs Player"), ("pve", "Player vs AI")],
                        db_index=True,
                        default="pvp",
                        max_length=12,
                    ),
                ),
                (
                    "finish_reason",
                    models.CharField(
                        choices=[
                            ("score", "Score"),
                            ("draw", "Draw"),
                            ("forfeit", "Forfeit"),
                            ("disconnect_forfeit", "Disconnect Forfeit"),
                            ("canceled", "Canceled"),
                            ("server_error", "Server Error"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="When the game session began (first tick / first move)."
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(help_text="When the game session ended."),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        default=0.0,
                        help_text="Game duration in seconds (finished_at - started_at).",
                    ),
                ),
                ("player1_score", models.IntegerField(default=0)),
                ("player2_score", models.IntegerField(default=0)),
                (
                    "ai_difficulty",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AI difficulty if this was a PvE game.",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Engine-specific metadata: final board state (TTT), ball speed (Pong), total moves, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "db_table": "matches",
                "ordering": ["-finished_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        help_text="Player slot in the game (1 or 2)."
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("draw", "Draw")],
                        db_index=True,
                        max_length=6,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0,
                        help_text="Player's final score (points in Pong, N/A for TTT).",
                    ),
                ),
                (
                    "xp_earned",
                    models.PositiveIntegerField(
                        default=0, help_text="XP awarded for this match."
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="games.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Player",
                "verbose_name_plural": "Match Players",
                "db_table": "match_players",
                "ordering": ["slot"],
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["-finished_at"], name="idx_match_finished"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["game_type", "-finished_at"], name="idx_match_type_finished"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["game_mode", "-finished_at"], name="idx_match_mode_finished"
            ),
        ),
        migrations.AddIndex(
            model_name="matchplayer",
            index=models.Index(fields=["user", "match"], name="idx_mp_user_match"),
        ),
        migrations.AlterUniqueTogether(
            name="matchplayer",
            unique_together={("match", "user")},
        ),
    ]
