# Generated by Django 5.1.15 on 2026-04-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="game_mode",
            field=models.CharField(
                choices=[("pvp", "Player vs Player"), ("pva", "Player vs AI")],
                db_index=True,
                default="pvp",
                max_length=12,
            ),
        ),
    ]
