# Generated by Django 5.1.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_match_game_mode"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="match",
                    name="ai_difficulty",
                ),
                migrations.AlterField(
                    model_name="match",
                    name="game_mode",
                    field=models.CharField(
                        choices=[("pvp", "Player vs Player")],
                        db_index=True,
                        default="pvp",
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
