# Generated by Django 5.1.15 on 2026-06-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmembership",
            name="read_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
