# Generated by Django 5.1.15 on 2026-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_channelmembership_notifications_muted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("emote", "Emote"),
                    ("system", "System"),
                    ("game_invite", "Game Invite"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
