# Generated by Django 5.1.15 on 2026-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_message_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="game_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="message",
            name="game_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
